import type { Metadata } from 'next';
// import { Inter } from 'next/font/google';
import '@/styles/globals.css';

import { twJoin } from 'tailwind-merge';
import { Provider } from '@/lib/theme/provider';

// export const inter = Inter({
//     subsets: ['latin'],
// });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
    icons: {
        icon: {
            url: '/favicon.ico',
            type: 'image/x-icon',
            sizes: '16x16',
        },
    },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang='en'>
            <body className={twJoin('body layout_root')}>
                <Provider>{children}</Provider>
            </body>
        </html>
    );
}
